//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST.Eg.EF.BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Lodgings = new HashSet<Lodging>();
            this.Trips = new HashSet<Trip>();
        }
    
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public byte[] Photo { get; set; }
        public string TravelWarnings { get; set; }
        public string ClimateInfo { get; set; }
    
        public virtual ICollection<Lodging> Lodgings { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
