//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST.Eg.EF.BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lodging
    {
        public Lodging()
        {
            this.InternetSpecials = new HashSet<InternetSpecial>();
        }
    
        public int LodgingId { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public decimal MilesFromNearestAirport { get; set; }
        public int destination_id { get; set; }
        public Nullable<int> PrimaryContactId { get; set; }
        public Nullable<int> SecondaryContactId { get; set; }
        public Nullable<int> MaxPersonsPerRoom { get; set; }
        public Nullable<bool> PrivateRoomsAvailable { get; set; }
        public string Entertainment { get; set; }
        public string Activities { get; set; }
        public string Discriminator { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<InternetSpecial> InternetSpecials { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
