//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST.Eg.EF.BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Lodgings = new HashSet<Lodging>();
            this.Lodgings1 = new HashSet<Lodging>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int PersonId { get; set; }
        public int SocialSecurityNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Address_AddressId { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public decimal Info_Weight_Reading { get; set; }
        public string Info_Weight_Units { get; set; }
        public decimal Info_Height_Reading { get; set; }
        public string Info_Height_Units { get; set; }
        public string Info_DietryRestrictions { get; set; }
        public byte[] Photo { get; set; }
        public string Caption { get; set; }
    
        public virtual ICollection<Lodging> Lodgings { get; set; }
        public virtual ICollection<Lodging> Lodgings1 { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
