//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST.Eg.EF.BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int ReservationId { get; set; }
        public System.DateTime DateTimeMade { get; set; }
        public Nullable<System.DateTime> PaidInFull { get; set; }
        public Nullable<int> Traveler_PersonId { get; set; }
        public Nullable<System.Guid> Trip_Identifier { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Person Person { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
