//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST.Eg.EF.BreakAwayModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Reservations = new HashSet<Reservation>();
            this.Activities = new HashSet<Activity>();
        }
    
        public System.Guid Identifier { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
        public decimal CostUSD { get; set; }
        public byte[] RowVersion { get; set; }
        public int DestinationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
